   ###  Scikit-learn API provides SelectKBest class for extracting best features of given dataset. 
     The SelectKBest method selects the features according to the k highest score. By changing the 'score_func' parameter we can apply the method for both classification and regression data. Selecting best features is important process when we prepare a large dataset for training. It helps us to eliminate less important part of the data and reduce a training time.



##    We'll start by loading the required libraries and functions.


In [1]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_regression
from sklearn.datasets import load_boston
from sklearn.datasets import load_iris
from numpy import array 

## SelectKBest for classification


In [16]:
##    First, we'll apply the SelectKBest model to classification data, Iris dataset. 
## We'll load the dataset and check the feature data dimension. 
## The 'data' property of the iris object is considered feature data. 


In [2]:
iris = load_iris()
x = iris.data
y = iris.target
 
print("Feature data dimension: ", x.shape) 


Feature data dimension:  (150, 4)


In [17]:
## Next, we'll define the model by using SelectKBest class.
## For classification we'll set 'chi2'  method as a scoring function. 
## The target number of features is defined by k parameter.
## Then we'll fit and transform method on training x and y data.

In [3]:
select = SelectKBest(score_func=chi2, k=3)
z = select.fit_transform(x,y)
 
print("After selecting best 3 features:", z.shape) 
 

After selecting best 3 features: (150, 3)


In [4]:
## We've selected 3 best features in x data. 

In [5]:
## To identify the selected features we use get_support() function and filter out them from the features name list.  

In [8]:
filter = select.get_support()
features = array(iris.feature_names)
 
print("All features:")
print(features)

print("Selected best 3:")
print(features[filter])

All features:
['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
Selected best 3:
['sepal length (cm)' 'petal length (cm)' 'petal width (cm)']


In [9]:
print(z)

[[5.1 1.4 0.2]
 [4.9 1.4 0.2]
 [4.7 1.3 0.2]
 [4.6 1.5 0.2]
 [5.  1.4 0.2]
 [5.4 1.7 0.4]
 [4.6 1.4 0.3]
 [5.  1.5 0.2]
 [4.4 1.4 0.2]
 [4.9 1.5 0.1]
 [5.4 1.5 0.2]
 [4.8 1.6 0.2]
 [4.8 1.4 0.1]
 [4.3 1.1 0.1]
 [5.8 1.2 0.2]
 [5.7 1.5 0.4]
 [5.4 1.3 0.4]
 [5.1 1.4 0.3]
 [5.7 1.7 0.3]
 [5.1 1.5 0.3]
 [5.4 1.7 0.2]
 [5.1 1.5 0.4]
 [4.6 1.  0.2]
 [5.1 1.7 0.5]
 [4.8 1.9 0.2]
 [5.  1.6 0.2]
 [5.  1.6 0.4]
 [5.2 1.5 0.2]
 [5.2 1.4 0.2]
 [4.7 1.6 0.2]
 [4.8 1.6 0.2]
 [5.4 1.5 0.4]
 [5.2 1.5 0.1]
 [5.5 1.4 0.2]
 [4.9 1.5 0.2]
 [5.  1.2 0.2]
 [5.5 1.3 0.2]
 [4.9 1.4 0.1]
 [4.4 1.3 0.2]
 [5.1 1.5 0.2]
 [5.  1.3 0.3]
 [4.5 1.3 0.3]
 [4.4 1.3 0.2]
 [5.  1.6 0.6]
 [5.1 1.9 0.4]
 [4.8 1.4 0.3]
 [5.1 1.6 0.2]
 [4.6 1.4 0.2]
 [5.3 1.5 0.2]
 [5.  1.4 0.2]
 [7.  4.7 1.4]
 [6.4 4.5 1.5]
 [6.9 4.9 1.5]
 [5.5 4.  1.3]
 [6.5 4.6 1.5]
 [5.7 4.5 1.3]
 [6.3 4.7 1.6]
 [4.9 3.3 1. ]
 [6.6 4.6 1.3]
 [5.2 3.9 1.4]
 [5.  3.5 1. ]
 [5.9 4.2 1.5]
 [6.  4.  1. ]
 [6.1 4.7 1.4]
 [5.6 3.6 1.3]
 [6.7 4.4 1.4]
 [5.6 4.5 

## SelectKBest for regression data


In [19]:
## We apply the same method for regression data only changing scoring function. 
## We'll load the Boston housing data set and check the feature data dimensions.


In [10]:
boston = load_boston()
x = boston.data
y = boston.target

print("Feature data dimension: ", x.shape)
 

Feature data dimension:  (506, 13)


In [20]:
## Next, we'll define the model by using SelectKBest class.
## For regression, we'll set 'f_regression'  method as a scoring function.
## The target number of features to select is 8.

In [11]:
select = SelectKBest(score_func=f_regression, k=8)
z = select.fit_transform(x, y) 
 
print("After selecting best 8 features:", z.shape) 

After selecting best 8 features: (506, 8)


In [21]:
## To identify the selected features we can use get_support() function and filter out them from the features list. 
## The z object contains selected x data. 

In [13]:
filter = select.get_support()
features = array(boston.feature_names)
 
print("All features:")
print(features)
 
print("Selected best 8:")
print(features[filter])

All features:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
Selected best 8:
['CRIM' 'INDUS' 'NOX' 'RM' 'RAD' 'TAX' 'PTRATIO' 'LSTAT']


In [14]:
print(z) 

[[6.3200e-03 2.3100e+00 5.3800e-01 ... 2.9600e+02 1.5300e+01 4.9800e+00]
 [2.7310e-02 7.0700e+00 4.6900e-01 ... 2.4200e+02 1.7800e+01 9.1400e+00]
 [2.7290e-02 7.0700e+00 4.6900e-01 ... 2.4200e+02 1.7800e+01 4.0300e+00]
 ...
 [6.0760e-02 1.1930e+01 5.7300e-01 ... 2.7300e+02 2.1000e+01 5.6400e+00]
 [1.0959e-01 1.1930e+01 5.7300e-01 ... 2.7300e+02 2.1000e+01 6.4800e+00]
 [4.7410e-02 1.1930e+01 5.7300e-01 ... 2.7300e+02 2.1000e+01 7.8800e+00]]
